# scripts/lib/targets.sh — the single declarative source of what gets linked.
#
# Row format: KIND|SOURCE_RELATIVE_TO_REPO|ABSOLUTE_TARGET
#   dir  - symlink a whole directory, so files added by a pull appear with no
#          install step. This is what makes "a pull is enough" true. Verified
#          2026-09-09: both tools read through a symlinked config directory.
#   file - symlink one file.
#   gen  - generated by lib/settings.sh, never linked. See that file for why.
#
# Deliberately absent from the Claude table: plugins/, projects/, agent-memory/,
# sessions/, session-env/, history.jsonl, telemetry/, usage-data/,
# shell-snapshots/, file-history/, cache/, paste-cache/, tasks/, jobs/, daemon*,
# ide/, chrome/, plans/, backups/, stats-cache.json, .last-cleanup. These are
# runtime state written by Claude Code; linking them into a Git repository would
# corrupt them and publish session history.
#
# Deliberately absent from the OpenCode table: node_modules/, package.json,
# package-lock.json, bun.lock — plugin-loader output, generated in place.

ad_targets_claude() {
    _h=$(ad_claude_home)
    cat <<ROWS
dir|shared|$_h/rules
dir|claude/agents|$_h/agents
dir|claude/commands|$_h/commands
dir|claude/skills|$_h/skills
dir|claude/workflows|$_h/workflows
dir|claude/output-styles|$_h/output-styles
dir|claude/themes|$_h/themes
file|claude/CLAUDE.md|$_h/CLAUDE.md
file|claude/keybindings.json|$_h/keybindings.json
file|claude/statusline.sh|$_h/statusline.sh
gen|claude/settings.json|$_h/settings.json
ROWS
}

# The `shared` row is belt and braces: whether OpenCode resolves the
# `instructions` glob against this directory or against the repository where the
# symlinked opencode.jsonc lives is unverified (see the verification document),
# and the link is correct under either answer.
ad_targets_opencode() {
    _h=$(ad_opencode_home)
    _m=$1
    cat <<ROWS
file|opencode/opencode.jsonc|$_h/opencode.jsonc
file|opencode/AGENTS.md|$_h/AGENTS.md
dir|opencode/agents|$_h/agents
dir|opencode/commands|$_h/commands
dir|opencode/skills|$_h/skills
dir|opencode/plugins|$_h/plugins
dir|shared|$_h/shared
file|opencode/machines/$_m.json|$_h/machine.json
ROWS
}

ad_row_kind()   { printf '%s\n' "$1" | cut -d'|' -f1; }
ad_row_source() { printf '%s\n' "$1" | cut -d'|' -f2; }
ad_row_target() { printf '%s\n' "$1" | cut -d'|' -f3; }
